[[links]]
url = "https://fffuel.co/dddraw/"
title = "Accéder à dddraw pour dessiner ses SVGs"
name = "dddraw"
text = "Dessines tes propres SVG à la main"
[[links]]
url = "https://mynoise.net/"
title = "Accéder à mynoise pour faire ses pistes de lo-fi"
name = "MyNoise"
text = "Créé des musiques d'ambiance facilement"
[[links]]
url = "https://azgaar.github.io/Fantasy-Map-Generator/"
title = "Accéder à azgaar pour généré facilement des cartes de fantasy"
name = "Azgaar"
text = "Créé en quelques cliques de superbes cartes de monde de fantasy"
[[links]]
url = "https://miro.com/"
title = "Accéder à Miro pour créer un tableau personnalisé"
name = "Miro"
text = "Créé ton board interactif comme tu le veux ! C'est une de mes application préférée ♥"
[[links]]
url = "https://demo.yunohost.org/yunohost/sso/"
title = "Accéder à Yunohost, un site qui rassemble tous les projets Open-Source à héberger chez-soi"
name = "Yunohost"
text = "Liste de services et applications Open Source à héberger chez-soi !"
[[links]]
url = "https://khubone.itch.io/5-min-gobelin"
title = "Accéder à 5 minutes Gobelin, un jeu de rôle en 5 minutes"
name = "5 min Gobelin"
text = "Vis la vie tumultueuse d'un gobelin qui se fait embarquer dans une aventure malgré lui :D"
